### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers_interpret'

### ISSUE THREAD

**Issue by owl0695** [Loreb92/relitc-counterfactuals#1]
Dear  authors,

I ran the model but it show 'ModuleNotFoundError: No module named 'transformers_interpret''
Thank you very much.

Best wishes.

**Comment by Loreb92** [comment]
Hi! Thanks for raising this issue. Can I please ask you to provide additional information about your OS, environment, and minimal instructions to reproduce your issue?

I would also check if 'transformers_interpret' has been installed correctly.

**Comment by owl0695** [comment]
Dear authors,

Environment is same as readme. The resaon of it is due to there is no 'transformers_interpret.py' file in scr folder.
So code 'from transformers_interpret import SequenceClassificationExplainer' in feature_importance_scorer.py  will show error. 

Best wishes.

**Comment by Loreb92** [comment]
Indeed, there shouldn't be a 'transformers_interpret.py' file in scr folder because 'transformers_interpret' is a package. Please, check if the package is correctly installed and working under the environment specified in the Readme (the environment should be activated as well).

Again, please provide additional information about your OS, environment, and minimal instructions to reproduce your issue.

**Comment by owl0695** [comment]
Dear authors,

It's working now, thanks a lot. 

Best wishes

**Comment by owl0695** [comment]
My OS is Windows 11
Environment is 3.10

Best wishes
